name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

      - name: Install npm
        run: npm install
      - name: Build
        run: npm run nx -- build
      - name: Lint
        run: npm run nx -- lint
      - name: Unit tests
        run: npm run nx -- test
